name: tdmpc2
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - glew=2.2.0
  - glib=2.78.4
  - pip=24.0
  - python=3.9
  - pytorch=2.6.0.dev20241112
  - pytorch-cuda=12.4
  - torchvision=0.15.2
  - pip:
    - dm-control==1.0.16
    - glfw==2.7.0
    - gymnasium==0.29.1
    - ffmpeg==1.4
    - imageio==2.34.1
    - imageio-ffmpeg==0.4.9
    - h5py==3.11.0
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - submitit==1.5.1
    - omegaconf==2.3.0
    - moviepy==1.0.3
    - mujoco==3.1.2
    - numpy==1.24.4
    - tensordict-nightly==2025.1.1
    - torchrl-nightly==2025.1.1
    - kornia==0.7.2
    - termcolor==2.4.0
    - tqdm==4.66.4
    - pandas==2.0.3
    - wandb==0.17.4
    ####################
    # Meta-World (nicklashansen fork, uses modern mujoco + gymnasium):
    - git+https://github.com/nicklashansen/metaworld.git
    ####################
    # ManiSkill2:
    # (requires gym==0.21.0 which occasionally breaks)
    # - mani-skill2==0.4.1
    ####################
    # MyoSuite:
    # - myosuite
    ####################
    # Classic MuJoCo/Box2d:
    # - swig
    # - gymnasium[box2d]
    ####################
